openapi: 3.0.0
info:
  title: EcoEngage Portal API
  version: 1.0.0
  description: APIs for managing comments in the EcoEngage Portal.

servers:
  - url: https://example.com/api/v1
    description: Production server

paths:
  /posts/{postId}/comments:
    get:
      summary: Get comments for a post
      parameters:
        - name: postId
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer
      responses:
        "200":
          description: List of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Comment"
        "401":
          description: Unauthorized
        "404":
          description: PostCard not found

    post:
      summary: Add a comment to a post
      parameters:
        - name: postId
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewComment"
      responses:
        "201":
          description: CommentCard added successfully
        "401":
          description: Unauthorized
        "404":
          description: PostCard not found
        "400":
          description: Bad request

  /posts/{postId}/comments/{commentId}:
    put:
      summary: Update a comment
      parameters:
        - name: postId
          in: path
          required: true
          description: ID of the post containing the comment
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          description: ID of the comment to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateComment"
      responses:
        "200":
          description: CommentCard updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden (User is not authorized)
        "404":
          description: CommentCard not found

    delete:
      summary: Delete a comment
      parameters:
        - name: postId
          in: path
          required: true
          description: ID of the post containing the comment
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          description: ID of the comment to delete
          schema:
            type: integer
      responses:
        "204":
          description: CommentCard deleted successfully
        "401":
          description: Unauthorized
        "403":
          description: Forbidden (User is not authorized)
        "404":
          description: CommentCard not found
components:
  schemas:
    Comment:
      type: object
      properties:
        commentId:
          type: integer
          example: 1
        postId:
          type: integer
          example: 123
        authorId:
          type: integer
          example: 456
        timeStamp:
          type: string
          format: date-time
          example: "2024-03-20T12:00:00Z"
        commentContent:
          type: string
          example: "This is a comment."

    NewComment:
      type: object
      properties:
        postId:
          type: integer
          example: 123
        authorId:
          type: integer
          example: 456
        commentContent:
          type: string
          example: "This is a new comment."

    UpdateComment:
      type: object
      properties:
        commentContent:
          type: string
          example: "This is an updated comment."
      required:
        - commentContent
